name: Check JS Syntax

###########################################
# Start the job on push outside of master #
###########################################
on:
  push:
    branches-ignore: [main]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Perform Lint
        uses: github/super-linter@v3.17.0
        env:
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: eslintrc.json
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  notify:
    needs: build
    name: Send Pull Request to main
    runs-on: ubuntu-latest
    
    steps:
        - name: checkout
          uses: actions/checkout@v2
          
        - name: pull-request
          uses: repo-sync/pull-request@v2
          with:
            destination_branch: "main"
            pr_title: "Pulling ${{github.ref}} into main"
            pr_body: "*Automated PR*"
            pr_reviewer: "hebrusonline"
            pr_draft: true
            github_token: ${{ secrets.GITHUB_TOKEN }}